<?php

namespace Resto\BackendBundle\Repository;

/**
 * BuffetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuffetRepository extends \Doctrine\ORM\EntityRepository
{
}
