resto_front:
    resource: "@RestoFrontBundle/Resources/config/routing.yml"
    prefix:   /

resto_backend:
    resource: "@RestoBackendBundle/Resources/config/routing.yml"
    prefix:   /employe

app:
    resource: '@AppBundle/Controller/'
    type: annotation
